# TCP para ESP32
listener 1883
allow_anonymous true

# WebSocket para panel web (EasyPanel proxy)
listener 9001
protocol websockets
allow_anonymous true
socket_domain ipv4

# Persistencia
persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_type all

connection hivemq-bridge
address 1625d06f36584da49b2f76112ecb67f3.s1.eu.hivemq.cloud:8883
bridge_protocol_version mqttv311
remote_username ASG-J
remote_password Joyeuse2024
topic vfd/status out 0
topic vfd/cmd in 0
bridge_tls_version tlsv1.2
bridge_capath /etc/ssl/certs/
start_type automatic
restart_timeout 5
